# ===================================================================
# Config Service - Default Profile Configuration (for Local Env)
# ===================================================================
server:
  port: 8888

spring:
  application:
    # Spring Cloud에서 서비스를 식별하기 위한 이름
    name: config-service

  cloud:
    config:
      server:
        git:
          # 다른 마이크로서비스들의 설정 파일이 저장된 외부 Git 리포지토리 주소
          uri: https://github.com/L-a-z-e/portal-universe-config-repo.git
          # Git 리포지토리에서 사용할 기본 브랜치
          default-label: main

eureka:
  instance:
    prefer-ip-address: false
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true